import Navbar from '../components/Navbar';
import Footer from '../components/Footer';
import Head from 'next/head';

export default function MainLayout({ children }) {
    return (
        <>
            <Head>
                <title>Nuggets - Tasty Knowledge.</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Navbar />
            <div className="content"></div>
            {children}
            <Footer />
        </>
    );
}
