# Generated by Django 3.2.6 on 2021-08-06 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuggets', '0006_auto_20210806_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='id_uuid',
            field=models.UUIDField(auto_created=True, null=True),
        ),
    ]
