# Generated by Django 3.2.6 on 2021-08-07 12:53

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('nuggets', '0009_auto_20210806_1745'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'default_manager_name': 'published_mng', 'verbose_name': 'Quiz', 'verbose_name_plural': 'Quizzes'},
        ),
        migrations.AlterModelManagers(
            name='quiz',
            managers=[
                ('published_mng', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('body', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='nuggets.quiz')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
