import Navbar from './Navbar';
import Footer from './Footer';
import { Container } from 'semantic-ui-react';
import Head from 'next/head';

export default function Layout({ children }) {
    return (
        <>
            <Head>
                <title>Nuggets - Tasty Knowledge.</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Navbar />
            <Container>{children}</Container>
            <Footer />
        </>
    );
}
