import Head from 'next/head';

export interface AboutProps {}

const About: React.SFC<AboutProps> = () => {
    return (
        <>
            <Head>
                <title>Nuggets | About</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div>
                <h1>Test</h1>
                <p>This is testing the new snippers lib</p>
            </div>
        </>
    );
};

export default About;
