# Generated by Django 3.2.6 on 2021-08-06 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuggets', '0003_quiz_pub_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='pub_date',
            new_name='published',
        ),
        migrations.AddField(
            model_name='quiz',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='slug',
            field=models.SlugField(max_length=250, null=True, unique_for_date='publish'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10),
        ),
        migrations.AddField(
            model_name='quiz',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
