# Generated by Django 3.2.6 on 2021-08-06 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuggets', '0005_auto_20210806_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='id_uuid',
            field=models.UUIDField(null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
