# Generated by Django 3.2.6 on 2021-08-06 17:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('nuggets', '0007_alter_quiz_id_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='id',
        ),
        migrations.AlterField(
            model_name='quiz',
            name='id_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='slug',
            field=models.SlugField(max_length=250, null=True, unique_for_date='published'),
        ),
    ]
