# Generated by Django 3.2.6 on 2021-08-06 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nuggets', '0008_auto_20210806_1701'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='id_uuid',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='tags',
        ),
    ]
