# Generated by Django 3.2.6 on 2021-08-08 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nuggets', '0012_auto_20210808_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='quiz',
            field=models.ForeignKey(default='e4291f69-6012-4f81-820c-e807363f1ec0', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='nuggets.quiz'),
            preserve_default=False,
        ),
    ]
