# Generated by Django 3.2.6 on 2021-08-08 12:23

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('nuggets', '0013_alter_comment_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
