# Generated by Django 3.2.6 on 2021-08-09 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nuggets', '0015_auto_20210808_1230'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'default_manager_name': 'published_mng', 'ordering': ('-published',), 'verbose_name': 'Quiz', 'verbose_name_plural': 'Quizzes'},
        ),
    ]
