# Generated by Django 3.2.6 on 2021-08-10 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuggets', '0016_alter_quiz_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
