# Generated by Django 3.2.6 on 2021-08-19 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuggets', '0019_auto_20210819_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answers',
            field=models.JSONField(null=True),
        ),
    ]
