# Generated by Django 3.2.6 on 2021-08-19 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuggets', '0020_question_answers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizattempt',
            name='status',
        ),
        migrations.AlterField(
            model_name='quiz',
            name='level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20, null=True),
        ),
    ]
