# Generated by Django 3.2.6 on 2021-08-19 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuggets', '0021_auto_20210819_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='meta',
        ),
        migrations.AddField(
            model_name='quiz',
            name='metadata',
            field=models.JSONField(blank=True, default=''),
        ),
    ]
