# Generated by Django 3.2.6 on 2021-08-19 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuggets', '0022_auto_20210819_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='metadata',
            field=models.JSONField(blank=True, default={}),
        ),
    ]
