# Generated by Django 3.2.6 on 2021-08-19 14:42

from django.db import migrations, models
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('nuggets', '0024_alter_quiz_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='_description_excerpt',
            field=models.TextField(default='Default description', editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quiz',
            name='description',
            field=model_utils.fields.SplitField(no_excerpt_field=True),
        ),
    ]
