# Generated by Django 3.2.6 on 2021-08-19 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuggets', '0025_auto_20210819_1442'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='_description_excerpt',
        ),
        migrations.AlterField(
            model_name='quiz',
            name='description',
            field=models.TextField(),
        ),
        migrations.AddField(
            model_name='quiz',
            name='topic',
            field=models.ManyToManyField(help_text='Select a topic for this quiz', to='nuggets.Topic'),
        ),
    ]
