# Generated by Django 3.2.6 on 2021-08-19 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuggets', '0026_auto_20210819_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='topic',
            field=models.ManyToManyField(help_text='Select a topic for this quiz', related_name='topics', to='nuggets.Topic'),
        ),
    ]
