# Generated by Django 3.2.6 on 2021-08-19 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuggets', '0027_alter_quiz_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizattempt',
            name='finishedAt',
        ),
        migrations.RemoveField(
            model_name='quizattempt',
            name='startedAt',
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='finished',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='started',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='status',
            field=models.CharField(choices=[('in-progress', 'In Progress'), ('complete', 'Complete')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='topic',
            field=models.ManyToManyField(help_text='Select a topic for this quiz', to='nuggets.Topic'),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='answers',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
