# Generated by Django 3.2.6 on 2021-08-19 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuggets', '0028_auto_20210819_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizattempt',
            name='started',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
